### ISSUE TITLE
Can not obtain the refresh_token using v2.0 of the Microsoft Identity

### ISSUE THREAD

**Issue by VelinGeorgiev** [jsessink/electron-angular-auth#1]
@jsessink , it seems that using v2.0 of the Microsoft Identity does not return refresh token in your example. Using the previous commit where v1.0 of the identity is used works just fine and the refresh token is being retrieved. 

Steps to repro:

- git clone https://github.com/jsessink/electron-angular-auth
- npm i
- place a console log at line: https://github.com/jsessink/electron-angular-auth/blob/5fffe266d99fcb4254ca3292efcb56ebdf431b61/electron/src/authenticator.ts#L149
- npm run electron
- authenticate using existing tenant account

Expected console log output:
```
{"token_type":"Bearer","scope":"AllSites.Read Sites.Read.All Sites.Search.All User.Read profile openid email","expires_in":3598,"ext_expires_in":3598,"access_token":"eyJ0..","refresh_token":".."}
```
Actual console log output:
```
{"token_type":"Bearer","scope":"AllSites.Read Sites.Read.All Sites.Search.All User.Read profile openid email","expires_in":3598,"ext_expires_in":3598,"access_token":"eyJ0.."}
```
Could that be an incorrect setup of my app so it is working in just v1.0?

**Comment by jsessink** [comment]
Hi there, the refresh token is only passed when the scope `offline_access` is added.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow

![image](https://user-images.githubusercontent.com/2416081/74749835-6125da80-5230-11ea-9ba0-c2c1db8d337d.png)

Hopefully I'll get around to updating all the packages on this repo someday.  It's actually been a while since I've messed with auth and Electron, but definitely feel free to ask if you run into any further issues. 🍻

**Comment by VelinGeorgiev** [comment]
How could have I missed that one 😄 ? Thank you very much @jsessink ! 

That is a brilliant and well thought example! Thanks!
